### ISSUE TITLE
when i install use    `npm install ex6-native-map --save`, i get an error. so i decide not ues this lib.

### ISSUE THREAD

**Issue by codebeautiful** [chad3814/es6-native-map#2]
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: node-v0.12.1.tar.gz local checksum 8ac59eea6f135c661cab8b054ca5f014452ba200343a0e9ca95e7d432a300b4d not match remote 30693376519c9736bcb22d44513252aee1d9463d78ac6c744ecb6d13fd91d680
gyp ERR! stack     at deref (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:299:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:340:13)
gyp ERR! stack     at IncomingMessage.emit (events.js:129:20)
gyp ERR! stack     at _stream_readable.js:908:16
gyp ERR! stack     at process._tickCallback (node.js:355:11)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/tong/work/code/qserver/node_modules/es6-native-map
gyp ERR! node -v v0.12.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "es6-native-map" "--save"
npm ERR! node v0.12.1
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! es6-native-map@2.0.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the es6-native-map@2.0.0 install script 'node-gyp configure build'.
npm ERR! This is most likely a problem with the es6-native-map package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls es6-native-map
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tong/work/code/qserver/npm-debug.log

**Comment by chad3814** [comment]
I dunno, I have the same setup, Darwin 14.1.0, node 0.12.1, npm 2.7.4 and node-gyp 1.0.3 and it worked for me

**Comment by chad3814** [comment]
if you still have npm-debug.log, send it in

**Comment by codebeautiful** [comment]
sorry, i find this error is about my wrong configure, thanks
