### ISSUE TITLE
Missing spread operator support in es6-native-map@3.5.1

### ISSUE THREAD

**Issue by valsadres** [chad3814/es6-native-map#9]
The spread operator ... works fine on the ES6 Map object, but generates an error on es6-native-map@3.5.1:

```
const Map = require('es6-native-map');
var m = new Map();
m.set('key1', 123); m.set('key2', 345); m.set('key3', 234);
console.log( 'Sorted Map:', [... m].sort((a,b)=>a[1]-b[1]) );
```

results in >> TypeError: undefined is not a function
while it should output >> Sorted Map: [ [ 'key1', 123 ], [ 'key3', 234 ], [ 'key2', 345 ] ]

**Comment by chad3814** [comment]
The iterator I made is wrong, according to the spec. I'll fix the iterator, and then set the Symbol.iterator property on the prototype to the entries function.

**Comment by chad3814** [comment]
I will publish 4.0.0 in the morning (after I verify I didn't mess anything else up)
